name: Build and Deploy to Prod Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip build-essential

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
        
      - name: Set up Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '24'

      - name: Set up npm registry
        run: pnpm config set registry https://registry.npmmirror.com/

      - name: Clean and Install Dependencies
        run: | 
          rm -rf node_modules
          rm -f pnpm-lock.yaml
          pnpm install --force

      # - name: Install Dependencies
      #  run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Deploy to Prod Branch
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: prod
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          force_orphan: true